name: sigma_home
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter_Regular.ttf
        - asset: fonts/Inter_Bold.ttf
          weight: 700
