// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATYMt0ridcAcV-mokJWCMMeg75jgWFkqs',
    appId: '1:324206692334:android:b4dff1004bba4e6de8f0ff',
    messagingSenderId: '324206692334',
    projectId: 'sigmahome-ed8f2',
    databaseURL:
        'https://sigmahome-ed8f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sigmahome-ed8f2.firebasestorage.app',
  );
}
