// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxWEtYiNbPPHxnFXnyvfCg3Od7X-d6Lg4',
    appId: '1:324206692334:web:9718aa8c1b589f85e8f0ff',
    messagingSenderId: '324206692334',
    projectId: 'sigmahome-ed8f2',
    authDomain: 'sigmahome-ed8f2.firebaseapp.com',
    storageBucket: 'sigmahome-ed8f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATYMt0ridcAcV-mokJWCMMeg75jgWFkqs',
    appId: '1:324206692334:android:9b307d26d7d5f887e8f0ff',
    messagingSenderId: '324206692334',
    projectId: 'sigmahome-ed8f2',
    databaseURL: 'https://sigmahome-ed8f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sigmahome-ed8f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNdsjuP2GxD44YC8DUeqG5ffpXl2DiCTg',
    appId: '1:324206692334:ios:75e10219d55af374e8f0ff',
    messagingSenderId: '324206692334',
    projectId: 'sigmahome-ed8f2',
    databaseURL: 'https://sigmahome-ed8f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sigmahome-ed8f2.firebasestorage.app',
    iosBundleId: 'com.example.sigmaHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNdsjuP2GxD44YC8DUeqG5ffpXl2DiCTg',
    appId: '1:324206692334:ios:75e10219d55af374e8f0ff',
    messagingSenderId: '324206692334',
    projectId: 'sigmahome-ed8f2',
    storageBucket: 'sigmahome-ed8f2.firebasestorage.app',
    iosBundleId: 'com.example.sigmaHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxWEtYiNbPPHxnFXnyvfCg3Od7X-d6Lg4',
    appId: '1:324206692334:web:99993f6df76fd40fe8f0ff',
    messagingSenderId: '324206692334',
    projectId: 'sigmahome-ed8f2',
    authDomain: 'sigmahome-ed8f2.firebaseapp.com',
    storageBucket: 'sigmahome-ed8f2.firebasestorage.app',
  );
}